cmake_minimum_required(VERSION 3.24)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
include("${root}/v8-version.cmake")
include("${root}/scripts/v8/args.cmake")
if(NOT TRIPLET MATCHES "^(x64-windows-star|arm64-osx-star|arm64-android-star|x64-android-star|arm64-ios-star|arm64-ios-simulator-star)$")
  message(FATAL_ERROR "Pass a supported TRIPLET")
endif()
if(NOT IS_DIRECTORY "${INPUT_DIR}")
  message(FATAL_ERROR "INPUT_DIR must contain Release/ and Debug/ artifacts")
endif()
star_v8_linkage(linkage)
string(TOLOWER "${linkage}" linkage)
set(base "star-v8-${STAR_V8_VERSION}-${TRIPLET}-${linkage}-sdk")
if(NOT DEFINED OUTPUT_DIR)
  set(OUTPUT_DIR "${root}/out/v8/${TRIPLET}")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(LOCK "${OUTPUT_DIR}/merge.lock" GUARD PROCESS TIMEOUT 0)
set(archive "${OUTPUT_DIR}/${base}.zip")
file(REMOVE "${archive}" "${archive}.sha256")
# A unique staging directory avoids mixing previous merges or input artifacts.
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
set(work "${OUTPUT_DIR}/merge-${nonce}")
set(merged "${work}/merged/${base}")
foreach(configuration Release Debug)
  string(TOLOWER "${configuration}" config)
  set(input "${INPUT_DIR}/${configuration}/${base}-${config}.zip")
  if(NOT EXISTS "${input}" OR NOT EXISTS "${input}.sha256")
    message(FATAL_ERROR "Missing validated ${configuration} artifact: ${input}")
  endif()
  file(READ "${input}.sha256" expected)
  file(SHA256 "${input}" actual)
  if(NOT expected STREQUAL "${actual}  ${base}-${config}.zip\n")
    message(FATAL_ERROR "Checksum mismatch: ${input}")
  endif()
  file(ARCHIVE_EXTRACT INPUT "${input}" DESTINATION "${work}/${config}")
  set(part "${work}/${config}/${base}")
  foreach(required "provenance/identity.txt" "provenance/build-${config}.txt"
      "provenance/${config}-args.gn" "${config}/include/v8-gn.h"
      "share/v8/V8Config.cmake" "share/v8/V8ConfigVersion.cmake")
    if(NOT EXISTS "${part}/${required}")
      message(FATAL_ERROR "Incomplete ${configuration} SDK: ${required}")
    endif()
  endforeach()
  file(READ "${part}/provenance/identity.txt" identity)
  foreach(field "v8=${STAR_V8_REVISION}" "triplet=${TRIPLET}" "linkage=${linkage}")
    string(FIND "\n${identity}" "\n${field}\n" found)
    if(found EQUAL -1)
      message(FATAL_ERROR "SDK identity mismatch: ${field}")
    endif()
  endforeach()
  file(GLOB_RECURSE files LIST_DIRECTORIES false RELATIVE "${part}" "${part}/*")
  foreach(relative IN LISTS files)
    if(EXISTS "${merged}/${relative}")
      file(SHA256 "${part}/${relative}" incoming)
      file(SHA256 "${merged}/${relative}" existing)
      if(NOT incoming STREQUAL existing)
        message(FATAL_ERROR "Release/Debug SDK files differ: ${relative}")
      endif()
    else()
      get_filename_component(directory "${relative}" DIRECTORY)
      file(MAKE_DIRECTORY "${merged}/${directory}")
      file(COPY_FILE "${part}/${relative}" "${merged}/${relative}")
    endif()
  endforeach()
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${archive}" --format=zip "${base}"
  WORKING_DIRECTORY "${work}/merged" COMMAND_ERROR_IS_FATAL ANY)
file(SHA256 "${archive}" checksum)
file(WRITE "${archive}.sha256" "${checksum}  ${base}.zip\n")
message(STATUS "Merged validated Release + Debug SDK: ${archive}")
