# Package the runtime dependency closure, including component ICU/zlib/Abseil.
if(v8_linkage STREQUAL "STATIC")
  file(COPY "${build}/obj/libv8_monolith.a" DESTINATION "${config_prefix}/lib")
else()
  set(runtime_dependencies)
  foreach(target v8 v8_libplatform)
    execute_process(COMMAND "${gn}" desc "${build}" ":${target}" runtime_deps
      WORKING_DIRECTORY "${source}" OUTPUT_VARIABLE dependencies
      COMMAND_ERROR_IS_FATAL ANY)
    string(REPLACE "\r" "" dependencies "${dependencies}")
    string(REPLACE "\n" ";" dependencies "${dependencies}")
    list(APPEND runtime_dependencies ${dependencies})
  endforeach()
  list(REMOVE_DUPLICATES runtime_dependencies)
  set(packaged_runtime)
  foreach(dependency IN LISTS runtime_dependencies)
    if(NOT dependency MATCHES "\\.(dll|dylib|so)$")
      continue()
    endif()
    # GN lists generated DLLs with './'; the bare Windows DLL names are
    # developer CRT/debugging tools copied by build/win:runtime_libs.
    if(CMAKE_HOST_WIN32 AND NOT dependency MATCHES "^\\./")
      continue()
    endif()
    get_filename_component(filename "${dependency}" NAME)
    file(COPY "${build}/${dependency}" DESTINATION "${config_prefix}/${runtime_subdir}")
    list(APPEND packaged_runtime "${filename}")
  endforeach()
  foreach(target v8 v8_libplatform v8_libbase)
    set(filename "${library_prefix}${target}${library_suffix}")
    if(NOT filename IN_LIST packaged_runtime)
      message(FATAL_ERROR "Missing shared runtime dependency: ${filename}")
    endif()
    if(CMAKE_HOST_WIN32)
      file(COPY "${build}/${filename}.lib" DESTINATION "${config_prefix}/lib")
    endif()
  endforeach()
  if(TRIPLET MATCHES "android")
    set(ndk_triple aarch64-linux-android)
    if(TRIPLET STREQUAL "x64-android-star")
      set(ndk_triple x86_64-linux-android)
    endif()
    # Implicit toolchain runtime libraries are not part of GN runtime_deps.
    file(COPY "${ndk}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/${ndk_triple}/libc++_shared.so"
      DESTINATION "${config_prefix}/${runtime_subdir}")
    list(APPEND packaged_runtime libc++_shared.so)
  endif()
  list(JOIN packaged_runtime "\n" runtime_manifest)
  file(WRITE "${sdk}/provenance/${config}-runtime.txt" "${runtime_manifest}\n")
endif()
