cmake_minimum_required(VERSION 3.24)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
include("${root}/v8-version.cmake")
if(NOT TRIPLET MATCHES "^(x64-windows-star|arm64-osx-star|arm64-android-star|x64-android-star|arm64-ios-star|arm64-ios-simulator-star)$"
    OR NOT ARCHIVE OR NOT SOURCE_SHA OR NOT EXPECTED_SHA256)
  message(FATAL_ERROR "Pass TRIPLET, ARCHIVE, SOURCE_SHA and EXPECTED_SHA256")
endif()
if(TRIPLET MATCHES "windows" AND NOT CMAKE_HOST_WIN32)
  message(FATAL_ERROR "Windows validation requires Visual Studio 2022 on Windows")
elseif(TRIPLET MATCHES "(osx|ios)")
  if(NOT CMAKE_HOST_APPLE)
    message(FATAL_ERROR "Apple validation requires Apple Silicon with Xcode")
  endif()
  execute_process(COMMAND uname -m OUTPUT_VARIABLE machine OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)
  if(NOT machine STREQUAL "arm64")
    message(FATAL_ERROR "Apple validation requires an arm64 host")
  endif()
elseif(TRIPLET MATCHES "android")
  file(TO_CMAKE_PATH "$ENV{ANDROID_NDK_HOME}" ndk)
  file(READ "${ndk}/source.properties" properties)
  if(NOT properties MATCHES "Pkg.Revision = 30\\.0\\.16248370")
    message(FATAL_ERROR "Use NDK 30.0.16248370")
  endif()
endif()
if(TRIPLET STREQUAL "x64-android-star" AND NOT ANDROID_SERIAL)
  message(FATAL_ERROR "Pass ANDROID_SERIAL for Android execution")
endif()
if(TRIPLET STREQUAL "arm64-ios-simulator-star" AND NOT SIMULATOR_UDID)
  message(FATAL_ERROR "Pass SIMULATOR_UDID for simulator execution")
endif()
file(SHA256 "${ARCHIVE}" actual)
if(NOT actual STREQUAL EXPECTED_SHA256)
  message(FATAL_ERROR "SDK checksum mismatch")
endif()
get_filename_component(name "${ARCHIVE}" NAME)
string(REGEX REPLACE "\\.zip$" "" base "${name}")
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
set(output "${root}/out/v8-validation/${TRIPLET}/${nonce}")
file(MAKE_DIRECTORY "${output}")
file(ARCHIVE_EXTRACT INPUT "${ARCHIVE}" DESTINATION "${output}/relocated")
set(prefix "${output}/relocated/${base}")
file(READ "${prefix}/provenance/identity.txt" identity)
foreach(field "source=${SOURCE_SHA}" "v8=${STAR_V8_REVISION}"
    "depot_tools=${STAR_DEPOT_TOOLS_REVISION}" "triplet=${TRIPLET}")
  string(FIND "\n${identity}" "\n${field}\n" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "SDK identity mismatch: ${field}")
  endif()
endforeach()
function(run_at directory)
  execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${directory}" COMMAND_ERROR_IS_FATAL ANY)
endfunction()
set(JOBS 4)
set(configurations Release Debug)
set(DEFER_SIMULATOR_TEST FALSE)
# Consume the existing SDK. No V8 checkout, GN generation or compilation.
include("${root}/scripts/v8/validate.cmake")
