cmake_minimum_required(VERSION 3.24)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
include("${root}/v8-version.cmake")
if(NOT CONFIGURATION MATCHES "^(Release|Debug)$" OR NOT INPUT_DIR OR NOT SIMULATOR_UDID)
  message(FATAL_ERROR "Pass CONFIGURATION=Release|Debug, INPUT_DIR and SIMULATOR_UDID")
endif()
set(TRIPLET arm64-ios-simulator-star)
string(TOLOWER "${CONFIGURATION}" config)
set(base "star-v8-${STAR_V8_VERSION}-${TRIPLET}-static-sdk")
set(name "${base}-${config}.zip")
get_filename_component(archive "${INPUT_DIR}/${name}" ABSOLUTE)
file(READ "${archive}.sha256" expected)
file(SHA256 "${archive}" actual)
if(NOT expected STREQUAL "${actual}  ${name}\n")
  message(FATAL_ERROR "Checksum mismatch: ${archive}")
endif()
if(NOT CMAKE_HOST_APPLE)
  message(FATAL_ERROR "Simulator execution requires an Apple Silicon Mac with Xcode")
endif()
execute_process(COMMAND uname -m OUTPUT_VARIABLE machine OUTPUT_STRIP_TRAILING_WHITESPACE
  COMMAND_ERROR_IS_FATAL ANY)
if(NOT machine STREQUAL "arm64")
  message(FATAL_ERROR "Simulator execution requires an Apple Silicon Mac")
endif()
set(output "${root}/out/v8-simulator/${config}")
file(MAKE_DIRECTORY "${output}")
# A fresh extraction avoids accepting leftover files from another candidate.
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef nonce)
set(prefix "${output}/relocated-${nonce}/${base}")
file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${output}/relocated-${nonce}")
file(READ "${prefix}/provenance/identity.txt" identity)
execute_process(COMMAND git -C "${root}" rev-parse HEAD OUTPUT_VARIABLE source_revision
  OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
foreach(field "source=${source_revision}" "v8=${STAR_V8_REVISION}"
    "depot_tools=${STAR_DEPOT_TOOLS_REVISION}" "triplet=${TRIPLET}" "linkage=static")
  string(FIND "\n${identity}" "\n${field}\n" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "SDK candidate identity mismatch: ${field}")
  endif()
endforeach()
function(run_at directory)
  execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${directory}"
    COMMAND_ERROR_IS_FATAL ANY)
endfunction()
set(JOBS 4)
set(configurations "${CONFIGURATION}")
set(DEFER_SIMULATOR_TEST FALSE)
# Build only the small consumer against the downloaded SDK; never rebuild V8.
include("${root}/scripts/v8/validate.cmake")
message(STATUS "Simulator validated SDK candidate: ${archive} (SHA256 ${actual})")
