# Consume only the relocated SDK, including in cross builds with root-only lookup.
function(star_test_boost target sdk)
  list(PREPEND CMAKE_PREFIX_PATH "${sdk}")
  list(PREPEND CMAKE_FIND_ROOT_PATH "${sdk}")
  find_package(Boost 1.90 CONFIG REQUIRED COMPONENTS container unordered dynamic_bitset
    PATHS "${sdk}/share/boost" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
  get_property(imported DIRECTORY PROPERTY IMPORTED_TARGETS)
  foreach(dependency IN LISTS imported)
    if(NOT dependency MATCHES "^Boost::")
      continue()
    endif()
    get_target_property(includes "${dependency}" INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(configurations "${dependency}" IMPORTED_CONFIGURATIONS)
    set(paths)
    if(includes)
      list(APPEND paths ${includes})
    endif()
    foreach(configuration IN LISTS configurations)
      foreach(property IMPORTED_LOCATION IMPORTED_IMPLIB)
        get_target_property(path "${dependency}" "${property}_${configuration}")
        if(path)
          list(APPEND paths "${path}")
        endif()
      endforeach()
    endforeach()
    foreach(path IN LISTS paths)
      cmake_path(IS_PREFIX sdk "${path}" NORMALIZE from_sdk)
      if(NOT from_sdk OR NOT EXISTS "${path}")
        message(FATAL_ERROR "${dependency} resolved outside the SDK or is missing: ${path}")
      endif()
    endforeach()
  endforeach()
  find_package(Threads REQUIRED)
  target_sources(${target} PRIVATE "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/boost.cpp")
  target_link_libraries(${target} PRIVATE
    Boost::container Boost::unordered Boost::dynamic_bitset Threads::Threads)
endfunction()
