cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED TEST_ROOT)
  message(FATAL_ERROR "Pass -DTEST_ROOT=<scratch directory>")
endif()
file(MAKE_DIRECTORY "${TEST_ROOT}/sdk/share/zlib" "${TEST_ROOT}/sysroot")
file(WRITE "${TEST_ROOT}/sdk/share/zlib/ZLIBConfig.cmake"
  "set(STAR_LOOKUP_FIXTURE_FOUND TRUE)\n")
set(CMAKE_PREFIX_PATH "${TEST_ROOT}/sdk")
set(CMAKE_FIND_ROOT_PATH "${TEST_ROOT}/sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
find_package(ZLIB CONFIG QUIET PATHS "${CMAKE_PREFIX_PATH}/share/zlib" NO_DEFAULT_PATH)
if(ZLIB_FOUND)
  message(FATAL_ERROR "Expected the original lookup to fail under root-only searching")
endif()

file(READ "${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt" consumer)
string(REGEX MATCH "find_package\\(ZLIB[^)]+\\)" lookup "${consumer}")
if(NOT lookup)
  message(FATAL_ERROR "Could not locate consumer package lookup")
endif()
cmake_language(EVAL CODE "${lookup}")
if(NOT ZLIB_FOUND OR NOT STAR_LOOKUP_FIXTURE_FOUND)
  message(FATAL_ERROR "Consumer did not find the explicit SDK config")
endif()
message(STATUS "Original root-only lookup failed; iOS consumer SDK lookup passed")