cmake_minimum_required(VERSION 3.24)
if(NOT TEST_ROOT OR NOT SCENARIO)
  message(FATAL_ERROR "Pass TEST_ROOT and SCENARIO")
endif()
file(MAKE_DIRECTORY "${TEST_ROOT}/container/Documents")

# Exercise the real smoke controller without Xcode, wall-clock waits or a device.
function(execute_process)
  cmake_parse_arguments(call "OUTPUT_STRIP_TRAILING_WHITESPACE;OUTPUT_QUIET;ERROR_QUIET"
    "TIMEOUT;RESULT_VARIABLE;OUTPUT_VARIABLE;ERROR_VARIABLE;OUTPUT_FILE;ERROR_FILE"
    "COMMAND" ${ARGN})
  file(APPEND "${TEST_ROOT}/calls.txt" "${call_COMMAND}\n")
  if("get_app_container" IN_LIST call_COMMAND)
    if(NOT call_TIMEOUT EQUAL 120)
      message(FATAL_ERROR "Container query must have a bounded 120-second timeout")
    endif()
    get_property(count GLOBAL PROPERTY container_calls)
    if(NOT count)
      set(count 0)
    endif()
    math(EXPR count "${count} + 1")
    set_property(GLOBAL PROPERTY container_calls "${count}")
    set(result 0)
    set(container "${TEST_ROOT}/container")
    set(error "")
    if(SCENARIO STREQUAL "timeout" OR (SCENARIO STREQUAL "retry" AND count EQUAL 1))
      set(result "Process terminated due to timeout")
      set(container "")
    elseif(SCENARIO STREQUAL "error")
      set(result 149)
      set(error "Unable to lookup in current state: Shutdown")
      set(container "")
    elseif(SCENARIO STREQUAL "missing")
      set(container "${TEST_ROOT}/does-not-exist")
    endif()
    set(${call_RESULT_VARIABLE} "${result}" PARENT_SCOPE)
    set(${call_OUTPUT_VARIABLE} "${container}" PARENT_SCOPE)
    set(${call_ERROR_VARIABLE} "${error}" PARENT_SCOPE)
  elseif("launch" IN_LIST call_COMMAND)
    string(REGEX MATCH "SIMCTL_CHILD_STAR_SMOKE_TOKEN=([0-9a-f]+)" match "${call_COMMAND}")
    set(token "${CMAKE_MATCH_1}")
    string(LENGTH "${token}" token_length)
    if(NOT token_length EQUAL 32)
      message(FATAL_ERROR "Missing launch token")
    endif()
    set(report "${token} STAR_IOS_SMOKE_PASSED")
    if(SCENARIO MATCHES "stale$")
      set(report "old-token STAR_IOS_SMOKE_PASSED")
    elseif(SCENARIO MATCHES "failed$")
      set(report "${token} STAR_IOS_SMOKE_FAILED")
    endif()
    if(SCENARIO STREQUAL "launch-timeout-late")
      set_property(GLOBAL PROPERTY pending_report "${report}")
    elseif(NOT SCENARIO STREQUAL "launch-timeout-empty")
      file(WRITE "${TEST_ROOT}/container/Documents/star-smoke-result.txt" "${report}\n")
    endif()
    file(WRITE "${call_OUTPUT_FILE}" "org.star-engine.binaries.smoke: 123\n")
    set(result 0)
    if(SCENARIO MATCHES "^launch-timeout-")
      set(result "Process terminated due to timeout")
    elseif(SCENARIO STREQUAL "launch-error")
      set(result 149)
    endif()
    set(${call_RESULT_VARIABLE} "${result}" PARENT_SCOPE)
  elseif("sleep" IN_LIST call_COMMAND)
    get_property(pending GLOBAL PROPERTY pending_report)
    if(pending)
      file(WRITE "${TEST_ROOT}/container/Documents/star-smoke-result.txt" "${pending}\n")
      set_property(GLOBAL PROPERTY pending_report "")
    endif()
  elseif("spawn" IN_LIST call_COMMAND)
    set(${call_RESULT_VARIABLE} 0 PARENT_SCOPE)
    set(${call_OUTPUT_VARIABLE} "mock simulator diagnostics" PARENT_SCOPE)
    set(${call_ERROR_VARIABLE} "" PARENT_SCOPE)
  elseif(NOT "sleep" IN_LIST call_COMMAND AND NOT "terminate" IN_LIST call_COMMAND)
    message(FATAL_ERROR "Unexpected command: ${call_COMMAND}")
  endif()
endfunction()

include("${CMAKE_CURRENT_LIST_DIR}/../../scripts/ios-simulator-smoke.cmake")
star_run_ios_smoke(test-udid "${TEST_ROOT}/simulator.log")
