cmake_minimum_required(VERSION 3.24)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${root}/v8-version.cmake")
include("${root}/scripts/v8/args.cmake")
star_v8_linkage(v8_linkage)
string(TOLOWER "${v8_linkage}" linkage_name)
if(NOT TRIPLET MATCHES "^(x64-windows-star|arm64-osx-star|arm64-android-star|x64-android-star|arm64-ios-star|arm64-ios-simulator-star)$")
  message(FATAL_ERROR "Pass -DTRIPLET=<one of the six Star triplets>")
endif()
file(TO_CMAKE_PATH "$ENV{ANDROID_NDK_HOME}" ndk)
if(PRINT_ARGS)
  foreach(config Release Debug)
    star_v8_args("${config}" args)
    message(STATUS "${TRIPLET} ${config}, V8 ${STAR_V8_VERSION}:\n${args}")
  endforeach()
  return()
endif()
if(TRIPLET MATCHES "windows" AND NOT CMAKE_HOST_WIN32)
  message(FATAL_ERROR "Windows V8 requires a Windows host with Visual Studio 2022")
elseif(TRIPLET MATCHES "(osx|ios)" AND NOT CMAKE_HOST_APPLE)
  message(FATAL_ERROR "Apple V8 targets require an Apple Silicon Mac with full Xcode")
elseif(TRIPLET MATCHES "android" AND NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  message(FATAL_ERROR "Android V8 uses the upstream Linux cross-compilation toolchain")
endif()
if(TRIPLET MATCHES "(osx|ios)")
  execute_process(COMMAND uname -m OUTPUT_VARIABLE machine OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)
  if(NOT machine STREQUAL "arm64")
    message(FATAL_ERROR "Use an Apple Silicon host")
  endif()
endif()
if(TRIPLET MATCHES "android")
  if(NOT EXISTS "${ndk}/build/cmake/android.toolchain.cmake")
    message(FATAL_ERROR "Set ANDROID_NDK_HOME to NDK 30.0.16248370")
  endif()
  file(READ "${ndk}/source.properties" ndk_properties)
  if(NOT ndk_properties MATCHES "Pkg.Revision = 30\\.0\\.16248370")
    message(FATAL_ERROR "This pipeline requires NDK 30.0.16248370")
  endif()
endif()
if(TRIPLET STREQUAL "x64-android-star" AND NOT ANDROID_SERIAL)
  message(FATAL_ERROR "Pass -DANDROID_SERIAL=<x86_64 emulator/device> for the execution test")
endif()
if(TRIPLET STREQUAL "arm64-ios-simulator-star" AND NOT SIMULATOR_UDID)
  message(FATAL_ERROR "Pass -DSIMULATOR_UDID=<booted iPhone simulator>")
endif()
if(NOT DEFINED JOBS)
  set(JOBS 4)
endif()
if(NOT JOBS MATCHES "^[1-9][0-9]*$")
  message(FATAL_ERROR "JOBS must be a positive integer")
endif()

set(work "${root}/out/v8")
set(depot "${work}/depot_tools")
set(checkout "${work}/source")
set(source "${checkout}/v8")
set(output "${work}/${TRIPLET}")
file(MAKE_DIRECTORY "${output}")
# gclient's shared checkout must not be synchronized by concurrent builds.
file(LOCK "${work}/build.lock" GUARD PROCESS TIMEOUT 0)
set(base "star-v8-${STAR_V8_VERSION}-${TRIPLET}-${linkage_name}-sdk")
set(sdk "${output}/${base}")
set(archive "${output}/${base}.zip")
# Invalidate older publication candidates even if source synchronization fails.
file(REMOVE "${archive}" "${archive}.sha256")
function(run_at directory)
  execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${directory}"
    COMMAND_ERROR_IS_FATAL ANY)
endfunction()
function(pinned_checkout directory url revision)
  if(NOT EXISTS "${directory}/.git")
    file(MAKE_DIRECTORY "${directory}")
    run_at("${directory}" git init)
    run_at("${directory}" git remote add origin "${url}")
    run_at("${directory}" git -c core.autocrlf=false fetch --depth 1 origin "${revision}")
    run_at("${directory}" git -c core.autocrlf=false checkout --detach "${revision}")
  endif()
  execute_process(COMMAND git -C "${directory}" rev-parse HEAD
    OUTPUT_VARIABLE actual OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  if(NOT actual STREQUAL revision)
    message(FATAL_ERROR "${directory} is not at pinned revision ${revision}; use a fresh out/v8 checkout")
  endif()
endfunction()
function(apply_patch_once directory patch)
  execute_process(COMMAND git apply --reverse --check "${patch}"
    WORKING_DIRECTORY "${directory}" RESULT_VARIABLE patched OUTPUT_QUIET ERROR_QUIET)
  if(NOT patched EQUAL 0)
    run_at("${directory}" git apply --check "${patch}")
    run_at("${directory}" git apply "${patch}")
  endif()
endfunction()
pinned_checkout("${depot}" https://chromium.googlesource.com/chromium/tools/depot_tools.git
  "${STAR_DEPOT_TOOLS_REVISION}")
pinned_checkout("${source}" https://chromium.googlesource.com/v8/v8.git "${STAR_V8_REVISION}")
set(ENV{DEPOT_TOOLS_UPDATE} 0)
set(ENV{DEPOT_TOOLS_WIN_TOOLCHAIN} 0)
set(ENV{VPYTHON_VIRTUALENV_ROOT} "${work}/vpython")
set(ENV{CIPD_CACHE_DIR} "${work}/cipd-cache")
if(CMAKE_HOST_WIN32)
  set(ENV{PATH} "${depot};$ENV{PATH}")
  set(gclient "${depot}/gclient.bat")
  set(gn "${source}/buildtools/win/gn.exe")
  set(ninja "${source}/third_party/ninja/ninja.exe")
  if(NOT EXISTS "${depot}/python3.bat")
    run_at("${depot}" cmd /c "${depot}/bootstrap/win_tools.bat")
  endif()
else()
  set(ENV{PATH} "${depot}:$ENV{PATH}")
  set(gclient "${depot}/gclient")
  set(ninja "${source}/third_party/ninja/ninja")
  if(CMAKE_HOST_APPLE)
    set(gn "${source}/buildtools/mac/gn")
  else()
    set(gn "${source}/buildtools/linux64/gn")
  endif()
endif()
set(target_os "[]")
if(TRIPLET MATCHES "android")
  set(target_os "['android']")
elseif(TRIPLET MATCHES "ios")
  set(target_os "['ios']")
endif()
if(NOT SKIP_SYNC)
  file(WRITE "${checkout}/.gclient"
    "solutions = [{'name': 'v8', 'url': 'https://chromium.googlesource.com/v8/v8.git', 'managed': False, 'custom_deps': {}, 'custom_vars': {}}]\ntarget_os = ${target_os}\n")
  run_at("${checkout}" "${gclient}" sync --no-history --shallow
    --revision "v8@${STAR_V8_REVISION}")
endif()
apply_patch_once("${source}" "${root}/patches/v8/generated-headers.patch")
apply_patch_once("${source}" "${root}/patches/v8/cppgc-generated-defines.patch")
if(TRIPLET MATCHES "ios")
  apply_patch_once("${source}/build" "${root}/patches/v8/ios-host-static.patch")
endif()
if(TRIPLET MATCHES "android")
  apply_patch_once("${source}/build" "${root}/patches/v8/android-ndk-unwind.patch")
endif()
if(TRIPLET MATCHES "windows")
  apply_patch_once("${source}" "${root}/patches/v8/windows-inline-exports.patch")
  file(COPY_FILE "${root}/scripts/v8/abseil-exports.py" "${source}/tools/star-absl-exports.py"
    ONLY_IF_DIFFERENT)
  apply_patch_once("${source}/third_party/abseil-cpp" "${root}/patches/v8/abseil-msvc-exports.patch")
endif()

file(REMOVE_RECURSE "${sdk}" "${output}/relocated")
file(MAKE_DIRECTORY "${sdk}/provenance" "${sdk}/share/v8")
set(v8_jitless FALSE)
if(TRIPLET MATCHES "ios")
  set(v8_jitless TRUE)
endif()
set(runtime_subdir lib)
set(library_prefix lib)
if(TRIPLET MATCHES "windows")
  set(runtime_subdir bin)
  set(library_prefix "")
  set(library_suffix .dll)
  set(runtime_suffix .dll)
elseif(TRIPLET MATCHES "android")
  set(library_suffix .cr.so)
  set(runtime_suffix .so)
else()
  set(library_suffix .dylib)
  set(runtime_suffix .dylib)
endif()
if(v8_linkage STREQUAL "STATIC")
  set(build_targets v8_monolith)
else()
  set(build_targets v8 v8_libplatform)
endif()
foreach(configuration Release Debug)
  string(TOLOWER "${configuration}" config)
  set(build "${source}/out/${TRIPLET}-${linkage_name}-${config}")
  file(MAKE_DIRECTORY "${build}")
  star_v8_args("${configuration}" args)
  file(WRITE "${build}/args.gn" "${args}")
  run_at("${source}" "${gn}" gen "${build}" --fail-on-unused-args)
  run_at("${source}" "${ninja}" -C "${build}" -j "${JOBS}" ${build_targets})
  set(config_prefix "${sdk}")
  if(configuration STREQUAL "Debug")
    set(config_prefix "${sdk}/debug")
  endif()
  include("${root}/scripts/v8/package-libraries.cmake")
  file(COPY "${build}/gen/include/v8-gn.h" DESTINATION "${sdk}/${config}/include")
  file(READ "${build}/gen/include/v8-gn.h" feature_header)
  foreach(feature V8_COMPRESS_POINTERS V8_ENABLE_SANDBOX)
    if(NOT feature_header MATCHES "#define ${feature} 1")
      message(FATAL_ERROR "${configuration} V8 is missing required feature ${feature}")
    endif()
  endforeach()
  file(COPY_FILE "${build}/args.gn" "${sdk}/provenance/${config}-args.gn")
endforeach()
file(COPY "${source}/include/" DESTINATION "${sdk}/include" FILES_MATCHING PATTERN "*.h")
# Preserve the licenses of bundled V8/ICU and all fetched third-party sources.
file(GLOB_RECURSE licenses LIST_DIRECTORIES false RELATIVE "${source}"
  "${source}/LICENSE*" "${source}/third_party/*/LICENSE*"
  "${source}/third_party/*/COPYING*" "${source}/third_party/*/copyright")
foreach(license IN LISTS licenses)
  if(NOT license MATCHES "^(out/|\\.git/)")
    get_filename_component(directory "${license}" DIRECTORY)
    file(COPY "${source}/${license}" DESTINATION "${sdk}/share/v8/licenses/${directory}")
  endif()
endforeach()
configure_file("${root}/scripts/v8/V8Config.cmake.in" "${sdk}/share/v8/V8Config.cmake" @ONLY)
include(CMakePackageConfigHelpers)
write_basic_package_version_file("${sdk}/share/v8/V8ConfigVersion.cmake"
  VERSION "${STAR_V8_VERSION}" COMPATIBILITY SameMajorVersion)
file(COPY "${root}/v8-version.cmake" "${root}/scripts/v8/args.cmake"
  "${root}/patches/v8" "${source}/DEPS" "${checkout}/.gclient"
  DESTINATION "${sdk}/provenance")
file(COPY "${root}/scripts/v8/abseil-exports.py" DESTINATION "${sdk}/provenance")
execute_process(COMMAND git -C "${root}" rev-parse HEAD OUTPUT_VARIABLE source_revision
  OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
file(WRITE "${sdk}/provenance/build.txt"
  "source=${source_revision}\nv8=${STAR_V8_REVISION}\ndepot_tools=${STAR_DEPOT_TOOLS_REVISION}\ntriplet=${TRIPLET}\nconfigurations=Release,Debug\nlinkage=${linkage_name}\npointer_compression=true\nsandbox=true\ncmake=${CMAKE_VERSION}\nhost=${CMAKE_HOST_SYSTEM}\n")
if(TRIPLET MATCHES "android")
  file(COPY "${ndk}/source.properties" DESTINATION "${sdk}/provenance")
  file(GLOB ndk_notices "${ndk}/NOTICE*")
  if(NOT ndk_notices)
    message(FATAL_ERROR "Missing NDK notices for the bundled libc++_shared.so")
  endif()
  file(COPY ${ndk_notices} DESTINATION "${sdk}/share/v8/licenses/android-ndk")
endif()
run_at("${output}" "${CMAKE_COMMAND}" -E tar cf "${archive}" --format=zip "${base}")
file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${output}/relocated")
set(prefix "${output}/relocated/${base}")
include("${root}/scripts/v8/validate.cmake")
file(SHA256 "${archive}" checksum)
file(WRITE "${archive}.sha256" "${checksum}  ${base}.zip\n")
message(STATUS "Validated V8 SDK: ${archive}")
